var tableArr1 = 
    [
        [ 
            {element:"Hydrogen"},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:"Helium"}
        ],

        [
            {element:"Lithium"},
            {element:"Beryllium"},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:"Boron"},
            {element:"Carbon"},
            {element:"Nitrogen"},
            {element:"Oxygen"},
            {element:"Fluorine"},
            {element:"Neon"}
        ],

        [
            {element:"Sodium"},
            {element:"Magnesium"},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:-1},
            {element:"Aluminium"},
            {element:"Silicon"},
            {element:"Phosphorus"},
            {element:"Sulfur"},
            {element:"Chlorine"},
            {element:"Argon"}
        ],

        [
            {element:"Potassium"},
            {element:"Calium"},
            {element:"Scandium"},
            {element:"Titanium"},
            {element:"Vanadium"},
            {element:"Chromium"},
            {element:"Manganese"},
            {element:"Iron"},
            {element:"Cobalt"},
            {element:"Nickel"},
            {element:"Copper"},
            {element:"Zinc"},
            {element:"Gallium"},
            {element:"Germainium"},
            {element:"Arsenic"},
            {element:"Selenium"},
            {element:"Bromine"},
            {element:"Krypton"}
        ],

        [
            {element:"Rubidium"},
            {element:"Strontium"},
            {element:"Yttrium"},
            {element:"Zirconium"},
            {element:"Niobium"},
            {element:"Molybdenum"},
            {element:"Technetium"},
            {element:"Ruthenium"},
            {element:"Rhodium"},
            {element:"Palladium"},
            {element:"Silver"},
            {element:"Cadmium"},
            {element:"Indium"},
            {element:"Tin"},
            {element:"Antimony"},
            {element:"Tellerium"},
            {element:"Iodine"},
            {element:"Xenon"}
            
        ],

        [
            {element:"Cesium"},
            {element:"Barium"},
            {element:"Lanthanum"},
            {element:"Hafnium"},
            {element:"Tantalum"},
            {element:"Tungsten"},
            {element:"Rhenium"},
            {element:"Osmium"},
            {element:"Iridium"},
            {element:"Platinum"},
            {element:"Gold"},
            {element:"Mercury"},
            {element:"Thallium"},
            {element:"Leab"},
            {element:"Bismuth"},
            {element:"Polonium"},
            {element:"Astatine"},
            {element:"Radon"}
        ],

        [
            {element:"Francium"},
            {element:"Radium"},
            {element:"Actinium"},
            {element:"Rutherfordium"},
            {element:"Dubnium"},
            {element:"Seaborgium"},
            {element:"Bohrium"},
            {element:"Hassium"},
            {element:"Meitnerium"},
            {element:"Darmstadium"},
            {element:"Roentegium"},
            {element:"Copernicium"},
            {element:"Nihonium"},
            {element:"Flerovium"},
            {element:"Moscovium"},
            {element:"Livermorium"},
            {element:"Tennessine"},
            {element:"Oganessum"}
        ],
    ];

for(var c = 0; c < 7; c++){
    for(var r = 0; r < 18; r++){
        if(tableArr1[c][r].element !== -1){
            $('#container').append("<div class = 'element'></div>");
        }
        else{
            $('#container').append("<div class = 'empty'></div>");
        }
    }
}